"""内置安全考核题库 —— **服务端权威副本**。

内容与前端 src/data/safetyContent.ts 的 buildSafetyQuestions() 一致；前端那份用于
离线模式兜底（未配置 VITE_API_BASE_URL 时），本文件用于在线模式的首次灌库。

本文件由前端内容生成，**请勿手工编辑题面**。要改题请在教师端「安全题库维护」里改
（改动会写进数据库并下发给所有学生），或改前端后重新生成此文件。

id 形如 sq-electric-001，与前端保持稳定一致，便于离线/在线对照。
"""

BUILTIN_SAFETY_QUESTIONS: list[dict] = [
    {
        "id": "sq-electric-001",
        "type": "single",
        "stem": "【电气安全】进行电气实验接线时，以下哪种操作正确？",
        "options": ["带电接线以节省时间", "断电接线，接好互查再通电", "直接用手摸接线端子确认", "只要电压低就可以不检查"],
        "answer": 1,
        "knowledgePoint": "断电接线",
        "difficulty": 1,
        "safetyCategory": "electric",
    },
    {
        "id": "sq-electric-002",
        "type": "single",
        "stem": "【电气安全】发现电器设备冒烟或有焦糊味，首先应当？",
        "options": ["继续观察一会", "立即切断电源", "用水浇灭", "找老师再说"],
        "answer": 1,
        "knowledgePoint": "异常即断电",
        "difficulty": 1,
        "safetyCategory": "electric",
    },
    {
        "id": "sq-electric-003",
        "type": "multiple",
        "stem": "【电气安全】以下哪些是电气实验必须遵守的规范？（多选）",
        "options": ["穿绝缘鞋", "长发扎起", "佩戴金属饰品增加导电性", "接好线路互查再通电"],
        "answer": [0, 1, 3],
        "knowledgePoint": "基本要求",
        "difficulty": 1,
        "safetyCategory": "electric",
    },
    {
        "id": "sq-electric-004",
        "type": "judge",
        "stem": "【电气安全】有人触电时，应立即用手拉开触电者。（判断）",
        "options": ["正确", "错误"],
        "answer": False,
        "knowledgePoint": "触电急救",
        "difficulty": 1,
        "safetyCategory": "electric",
    },
    {
        "id": "sq-thermal-005",
        "type": "single",
        "stem": "【热学安全】熄灭酒精灯的正确方法是？",
        "options": ["用嘴吹灭", "用灯帽盖灭", "用水浇灭", "甩一甩灭掉"],
        "answer": 1,
        "knowledgePoint": "酒精灯使用",
        "difficulty": 1,
        "safetyCategory": "thermal",
    },
    {
        "id": "sq-thermal-006",
        "type": "single",
        "stem": "【热学安全】加热试管时，管口应该朝向？",
        "options": ["朝向自己方便观察", "朝向同学便于协作", "朝向无人的方向", "任意方向都行"],
        "answer": 2,
        "knowledgePoint": "试管口不对人",
        "difficulty": 1,
        "safetyCategory": "thermal",
    },
    {
        "id": "sq-thermal-007",
        "type": "multiple",
        "stem": "【热学安全】关于热玻璃器皿的处理，正确的是？（多选）",
        "options": ["立即放入冷水快速冷却", "放在石棉网上自然冷却", "用干布包裹拿取", "先擦干外壁水珠再加热"],
        "answer": [1, 3],
        "knowledgePoint": "热胀冷缩防范",
        "difficulty": 1,
        "safetyCategory": "thermal",
    },
    {
        "id": "sq-thermal-008",
        "type": "judge",
        "stem": "【热学安全】轻度烫伤后应立即用大量流动冷水冲洗 15 分钟以上。（判断）",
        "options": ["正确", "错误"],
        "answer": True,
        "knowledgePoint": "烫伤处理",
        "difficulty": 1,
        "safetyCategory": "thermal",
    },
    {
        "id": "sq-optical-009",
        "type": "single",
        "stem": "【光学安全】光学实验中对激光的操作，正确的是？",
        "options": ["用眼睛直视激光束校准光路", "佩戴专用激光防护镜", "激光光路与坐姿人眼齐平", "用手擦激光镜片上的灰尘"],
        "answer": 1,
        "knowledgePoint": "激光防护",
        "difficulty": 1,
        "safetyCategory": "optical",
    },
    {
        "id": "sq-optical-010",
        "type": "single",
        "stem": "【光学安全】拿取光学透镜的正确姿势是？",
        "options": ["手指捏住透镜光学面", "手指拿住磨砂边缘", "用纸巾包裹光学面", "随意拿取只要不掉就行"],
        "answer": 1,
        "knowledgePoint": "光学元件操作",
        "difficulty": 1,
        "safetyCategory": "optical",
    },
    {
        "id": "sq-optical-011",
        "type": "multiple",
        "stem": "【光学安全】以下关于紫外灯的操作正确的是？（多选）",
        "options": ["人必须离开房间", "穿防护服戴护目镜", "长时间注视观察紫外线效果", "开启后可以短时间直视"],
        "answer": [0, 1],
        "knowledgePoint": "紫外防护",
        "difficulty": 1,
        "safetyCategory": "optical",
    },
    {
        "id": "sq-optical-012",
        "type": "judge",
        "stem": "【光学安全】清洁光学元件表面时可以用普通纸巾。（判断）",
        "options": ["正确", "错误"],
        "answer": False,
        "knowledgePoint": "光学清洁",
        "difficulty": 1,
        "safetyCategory": "optical",
    },
    {
        "id": "sq-mechanical-013",
        "type": "single",
        "stem": "【机械安全】操作车床、钻床等旋转机械时，以下哪项是错误的？",
        "options": ["戴工作帽扎起长发", "佩戴防护眼镜", "戴手套操作防止擦伤", "装夹牢固后开机"],
        "answer": 2,
        "knowledgePoint": "旋转不戴手套",
        "difficulty": 1,
        "safetyCategory": "mechanical",
    },
    {
        "id": "sq-mechanical-014",
        "type": "single",
        "stem": "【机械安全】清理金属切屑时应该？",
        "options": ["用嘴吹掉", "用手抹干净", "用毛刷或钩子清理", "用吸尘器吸"],
        "answer": 2,
        "knowledgePoint": "切屑清理",
        "difficulty": 1,
        "safetyCategory": "mechanical",
    },
    {
        "id": "sq-mechanical-015",
        "type": "multiple",
        "stem": "【机械安全】以下属于机械操作必须遵守的规范？（多选）",
        "options": ["长发盘入工作帽", "锐边打磨倒角后拿取", "测量工件时停机进行", "手套越厚越安全"],
        "answer": [0, 1, 2],
        "knowledgePoint": "基本机械安全",
        "difficulty": 1,
        "safetyCategory": "mechanical",
    },
    {
        "id": "sq-mechanical-016",
        "type": "judge",
        "stem": "【机械安全】手被机器夹住时，为了快速脱困应强行拉扯。（判断）",
        "options": ["正确", "错误"],
        "answer": False,
        "knowledgePoint": "夹手应急",
        "difficulty": 1,
        "safetyCategory": "mechanical",
    },
    {
        "id": "sq-radiation-017",
        "type": "single",
        "stem": "【辐射安全】辐射防护三大原则不包括以下哪项？",
        "options": ["时间防护（时间尽量短）", "距离防护（距离尽量远）", "屏蔽防护（加屏蔽层）", "营养防护（多吃保健品）"],
        "answer": 3,
        "knowledgePoint": "辐射防护三原则",
        "difficulty": 1,
        "safetyCategory": "radiation",
    },
    {
        "id": "sq-radiation-018",
        "type": "single",
        "stem": "【辐射安全】取放放射源的正确方式是？",
        "options": ["徒手快速抓取", "使用长柄工具", "戴普通棉质手套拿取", "用纸包着拿"],
        "answer": 1,
        "knowledgePoint": "放射源操作",
        "difficulty": 1,
        "safetyCategory": "radiation",
    },
    {
        "id": "sq-radiation-019",
        "type": "multiple",
        "stem": "【辐射安全】进入辐射实验区域，正确的做法是？（多选）",
        "options": ["佩戴个人剂量计", "孕妇可以陪同进入", "停留时间尽量短", "不用的放射源放回铅罐"],
        "answer": [0, 2, 3],
        "knowledgePoint": "辐射区管理",
        "difficulty": 1,
        "safetyCategory": "radiation",
    },
    {
        "id": "sq-radiation-020",
        "type": "judge",
        "stem": "【辐射安全】发现放射源丢失，应立即报告并组织人员搜寻。（判断）",
        "options": ["正确", "错误"],
        "answer": False,
        "knowledgePoint": "源丢失应急",
        "difficulty": 1,
        "safetyCategory": "radiation",
    },
    {
        "id": "sq-chemical-021",
        "type": "single",
        "stem": "【化学安全】稀释浓硫酸的正确方法是？",
        "options": ["将水快速倒入浓硫酸中", "将浓硫酸缓慢倒入水中并搅拌", "两者同时倒入烧杯", "先加什么都行只要搅拌"],
        "answer": 1,
        "knowledgePoint": "酸入水",
        "difficulty": 1,
        "safetyCategory": "chemical",
    },
    {
        "id": "sq-chemical-022",
        "type": "single",
        "stem": "【化学安全】皮肤不慎溅到强酸强碱，第一步应该？",
        "options": ["立即涂抹药膏", "用布擦掉", "大量流动水冲洗 15 分钟以上", "等老师来处理"],
        "answer": 2,
        "knowledgePoint": "溅蚀处理",
        "difficulty": 1,
        "safetyCategory": "chemical",
    },
    {
        "id": "sq-chemical-023",
        "type": "multiple",
        "stem": "【化学安全】进入化学实验室，必须做到？（多选）",
        "options": ["穿棉质实验服并扣好袖口", "佩戴护目镜", "实验区不存放食物饮料", "实验前后洗手"],
        "answer": [0, 1, 2, 3],
        "knowledgePoint": "基本化学防护",
        "difficulty": 1,
        "safetyCategory": "chemical",
    },
    {
        "id": "sq-chemical-024",
        "type": "judge",
        "stem": "【化学安全】油类起火可以用水灭火。（判断）",
        "options": ["正确", "错误"],
        "answer": False,
        "knowledgePoint": "灭火常识",
        "difficulty": 1,
        "safetyCategory": "chemical",
    },
    {
        "id": "sq-combined-025",
        "type": "single",
        "stem": "【综合安全】综合类实验存在两种及以上高风险因素时，正确做法是？",
        "options": ["一个人小心操作即可", "两人以上协同操作", "只要操作快就没事", "减少步骤跳过安全检查"],
        "answer": 1,
        "knowledgePoint": "多风险双人",
        "difficulty": 1,
        "safetyCategory": "combined",
    },
    {
        "id": "sq-combined-026",
        "type": "single",
        "stem": "【综合安全】综合实验结束后的检查清单不应包含？",
        "options": ["所有热源电源已关闭", "试剂放射源归位", "门窗水电关好", "不用处理废液留给下组"],
        "answer": 3,
        "knowledgePoint": "检查清单",
        "difficulty": 1,
        "safetyCategory": "combined",
    },
    {
        "id": "sq-combined-027",
        "type": "multiple",
        "stem": "【综合安全】综合实验的应急预案升级包括？（多选）",
        "options": ["规划疏散路线和集合点", "配备复合式灭火器和急救设备", "指定安全员全程监控", "做完就走不用检查"],
        "answer": [0, 1, 2],
        "knowledgePoint": "应急预案",
        "difficulty": 1,
        "safetyCategory": "combined",
    },
    {
        "id": "sq-combined-028",
        "type": "judge",
        "stem": "【综合安全】机械与电气设备交叉使用时，应先断电再进行机械装配。（判断）",
        "options": ["正确", "错误"],
        "answer": True,
        "knowledgePoint": "先断电后机械",
        "difficulty": 1,
        "safetyCategory": "combined",
    },
    {
        "id": "sq-electric-extra-029",
        "type": "single",
        "stem": "【电气安全】通电前为什么要高喊\"通电了\"？",
        "options": ["仪式感", "提醒周围人员注意，防止误碰", "表示自己很厉害", "没有特别意义"],
        "answer": 1,
        "knowledgePoint": "通电提醒",
        "difficulty": 2,
        "safetyCategory": "electric",
    },
    {
        "id": "sq-thermal-extra-030",
        "type": "single",
        "stem": "【热学安全】加热液体时忘记加入沸石，应该？",
        "options": ["立即补加", "降温后再补加", "继续加热不管", "用玻璃棒搅拌代替"],
        "answer": 1,
        "knowledgePoint": "沸石补加",
        "difficulty": 2,
        "safetyCategory": "thermal",
    },
    {
        "id": "sq-optical-extra-031",
        "type": "single",
        "stem": "【光学安全】暗室操作时，以下做法正确的是？",
        "options": ["快速跑动节省时间", "预先熟悉物品位置，缓慢适应明暗", "开灯关灯随意切换", "水杯放在光路旁方便饮用"],
        "answer": 1,
        "knowledgePoint": "暗室操作",
        "difficulty": 2,
        "safetyCategory": "optical",
    },
    {
        "id": "sq-mechanical-extra-032",
        "type": "single",
        "stem": "【机械安全】使用台钻钻孔时，工件应如何固定？",
        "options": ["用手拿着就行", "台虎钳或专用夹具夹紧", "用脚踩着", "让同学按住"],
        "answer": 1,
        "knowledgePoint": "工件装夹",
        "difficulty": 2,
        "safetyCategory": "mechanical",
    },
    {
        "id": "sq-radiation-extra-033",
        "type": "single",
        "stem": "【辐射安全】关于个人剂量计的佩戴，正确的是？",
        "options": ["可以借给别人用", "佩戴在胸口或左衣领处", "放在口袋里就行", "不用时放在辐射旁边校准"],
        "answer": 1,
        "knowledgePoint": "剂量计佩戴",
        "difficulty": 2,
        "safetyCategory": "radiation",
    },
    {
        "id": "sq-chemical-extra-034",
        "type": "single",
        "stem": "【化学安全】汞（水银）撒落后正确的处理方式是？",
        "options": ["用扫把扫掉", "用硫磺粉覆盖", "用真空吸尘器吸", "直接倒入下水道"],
        "answer": 1,
        "knowledgePoint": "汞洒落",
        "difficulty": 2,
        "safetyCategory": "chemical",
    },
    {
        "id": "sq-combined-extra-035",
        "type": "single",
        "stem": "【综合安全】综合实验的安全员职责是什么？",
        "options": ["全程操作设备", "监控操作风险并提醒", "只负责记录数据", "只负责打扫卫生"],
        "answer": 1,
        "knowledgePoint": "安全员职责",
        "difficulty": 2,
        "safetyCategory": "combined",
    },
]


def build_safety_questions() -> list[dict]:
    """返回内置安全题（字面 camelCase 字段，与前端 Question 类型对齐）。"""
    return [dict(q) for q in BUILTIN_SAFETY_QUESTIONS]
